services:
  mysql:
    image: mysql:8.0
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: navettes
      MYSQL_USER: user
      MYSQL_PASSWORD: user_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin_container
    restart: always
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: root_password
    ports:
      - "8080:80"
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    restart: always 
    volumes:
      - ./:/var/www/html
    ports:
      - "8000:80"
    networks:
      - laravel_network

volumes:
  mysql_data:
  
networks:
  laravel_network: